name: Build Python App
description: Build Python app
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
      shell: bash

    #- run: |
     #   cd python
      #  pip install -r requirements.txt
       # python setup.py sdist
      #shell: bash
