name: Build Java App
description: Build Java using Maven or Gradle
runs:
  using: "composite"
  steps:
    #- run: ./java/gradlew build
     # shell: bash
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        #cache: maven
    - name: Build with Maven
      run: | 
        if [ -f java/pom.xml ]; then
          cd java
          mvn clean install
        else
          echo "No build file found (pom.xml or build.gradle)"
        fi
      shell: bash
